[package]
name = "server"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = { version = "0.6.18", features = ["ws", "headers", "tracing", "multipart", "macros"] }
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
